/**
 * Cross-platform port allocation and dev environment files for Roxzave.
 */
const fs = require("fs");
const net = require("net");
const path = require("path");

const rootDir = path.join(__dirname, "..");
const portFilePath = path.join(rootDir, ".dev-backend-port");
const envLocalPath = path.join(rootDir, ".env.development.local");

const DEFAULT_START = Number(process.env.ROXZAVE_PORT_START || 8000);
const DEFAULT_END = Number(process.env.ROXZAVE_PORT_END || 8099);

/**
 * Try binding to detect availability (handles WinError 10013 / EADDRINUSE).
 */
function probePort(port, host = "127.0.0.1") {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.unref();
    server.once("error", (err) => {
      resolve({ available: false, error: err });
    });
    server.once("listening", () => {
      server.close(() => resolve({ available: true }));
    });
    server.listen(port, host);
  });
}

async function allocateBackendPort(start = DEFAULT_START, end = DEFAULT_END) {
  const skipped = [];
  for (let port = start; port <= end; port++) {
    const result = await probePort(port);
    if (result.available) {
      return { port, skipped };
    }
    skipped.push({
      port,
      reason: formatPortError(result.error),
    });
  }
  throw new Error(`No free port between ${start} and ${end}. Close other apps or widen ROXZAVE_PORT_END.`);
}

function formatPortError(err) {
  if (!err) return "unavailable";
  if (err.code === "EADDRINUSE") return "in use";
  if (err.code === "EACCES" || err.code === "EACCESS") return "permission denied / reserved (WinError 10013)";
  return err.code || err.message || "unavailable";
}

function writeDevPortFiles(port) {
  fs.writeFileSync(portFilePath, String(port), "utf8");
  const envLines = [
    `# Auto-generated by Roxzave dev scripts — do not commit`,
    `ROXZAVE_BACKEND_PORT=${port}`,
    `VITE_BACKEND_PORT=${port}`,
    `VITE_API_URL=http://127.0.0.1:${port}`,
  ];
  fs.writeFileSync(envLocalPath, envLines.join("\n") + "\n", "utf8");
}

function readBackendPort() {
  if (process.env.ROXZAVE_BACKEND_PORT) {
    return Number(process.env.ROXZAVE_BACKEND_PORT);
  }
  if (fs.existsSync(portFilePath)) {
    const n = parseInt(fs.readFileSync(portFilePath, "utf8").trim(), 10);
    if (!Number.isNaN(n)) return n;
  }
  return DEFAULT_START;
}

function waitForPortFile(timeoutMs = 60_000) {
  const started = Date.now();
  return new Promise((resolve, reject) => {
    const tick = () => {
      if (fs.existsSync(portFilePath)) {
        resolve(readBackendPort());
        return;
      }
      if (Date.now() - started > timeoutMs) {
        reject(new Error("Timed out waiting for .dev-backend-port"));
        return;
      }
      setTimeout(tick, 200);
    };
    tick();
  });
}

async function printStartupDiagnostics(port, skipped = []) {
  const lines = [
    "",
    "══════════════════════════════════════════════════════",
    "  Roxzave Dev Startup Diagnostics",
    "══════════════════════════════════════════════════════",
  ];

  if (skipped.length > 0) {
    lines.push("  Port availability:");
    for (const s of skipped.slice(0, 5)) {
      lines.push(`    · ${s.port} — ${s.reason}`);
    }
    if (skipped.length > 5) {
      lines.push(`    · … and ${skipped.length - 5} more checked`);
    }
  } else {
    lines.push(`  Port availability: ${port} (default free)`);
  }

  lines.push(`  Selected backend port: ${port}`);
  lines.push(`  API URL: http://127.0.0.1:${port}`);
  lines.push(`  Health:  http://127.0.0.1:${port}/health`);
  lines.push(`  Port file: .dev-backend-port`);
  lines.push("──────────────────────────────────────────────────────");
  lines.push("  Database: bootstrapping via backend…");
  lines.push("  API:      starting after bootstrap…");
  lines.push("  Frontend: waits for /health then starts Vite");
  lines.push("══════════════════════════════════════════════════════");
  lines.push("");

  console.log(lines.join("\n"));
}

module.exports = {
  allocateBackendPort,
  writeDevPortFiles,
  readBackendPort,
  waitForPortFile,
  printStartupDiagnostics,
  portFilePath,
  envLocalPath,
  probePort,
  formatPortError,
};
